				 =============================================
				\tSCRIPT OF SITEORDERS STORE PROCEDURE
						YEMISI ADEOLUWA - 13/06/2018
			    - =============================================

Listed Opened Site Orders filtering by the Maximun ChargeDate

In [ ]:
ALTER PROCEDURE sp_OpenedSiteOrders
 @companyOutlet AS int
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from interfering with SELECT statements.
SET NOCOUNT ON;
    -- Insert statements for procedure here

DECLARE	@TODAY DATETIME = GETDATE()
DECLARE @ProcessFromDate DATETIME = '2018-04-01'
DECLARE @chargeDate DATETIME = '2017-06-01'

SELECT 		  so.SiteOrderId
			 ,cs.SiteName
			 ,so.OrderNo
			 ,co.[Description] 
			 ,s.[Description] 
			 ,MAX(ch.ChargeDateTime) 
			 ,c.Customer*			 
			 ,c.ASN**Code
			 ,so.PN*

FROM		 ED* AS so LEFT OUTER JOIN
             DD*.dbo.Charge AS ch ON so.SI*d = ch.SI*d 

WHERE		S*			 AND (so.Va*til IS 
80903,
70838,
85208,
85686,
67933,
70585,
83218,
83314,
87554,
73573,
64777,
84655,
72975,
73118,
83544,
80746,
67628,
51421,
86049,
86070,
68040,
73418,
67481,
69652,
81159,
81053,
86213,
49432,
85343,
85344,
82106,
81241,
82932,
86002,
86633,
9575,
70302,
74112,
24976,
67578,
68613,
67940,
68543,
74285,
21478,
74068,
66150,
66151,
66147,
66149,
67582,
67583,
75611,
76145,
71221,
78758,
69863,
75864,
67996,
68069,
86511,
68863,
67939,
21609,
85979,
75865,
24921,
68948,
70635,
68165,
67761,
68813,
35268,
68289,
73806,
78345,
80028,
70256,
73214,
69577,
83441,
73419,
75315,
71270,
86863,
73538,
85010,
85019,
74790,
75584,
82464,
74829,
81603,
74980,
83496,
81042,
83165,
86133)
	GROUP BY so.SiteOrderId
			 ,cs.SiteName
			 ,so.OrderNo
			 ,c.CustomerName
			 ,c.ARAccountCode 
			 ,co.[Description]
			 ,s.[Description]
			 ,so.Pso.S*Id
			 ,cs.SN**
			 ,so.ON*
			 ,co.D*
			 ,s.DD*
			 ,c.C*
			 ,c.Ac*
			 ,so.PF*outputs